development:
  app_id: 117619831583011
  secret_key: 2eab4df3fb3f1397d6f6ddca929db4af
  canvas_page_name:
  callback_url: http://localhost:3000/
  pretty_errors: true
  set_asset_host_to_callback_url: true
  tunnel:
    public_host_username:
    public_host:
    public_port: 4007
    local_port: 3000
test:
  app_id: 117619831583011
  secret_key: 2eab4df3fb3f1397d6f6ddca929db4af
  canvas_page_name:
  callback_url: http://localhost:3000/
  pretty_errors: true
  set_asset_host_to_callback_url: true
  tunnel:
    public_host_username:
    public_host:
    public_port: 4007
    local_port: 3000
production:
  app_id: 117619831583011
  secret_key: 2eab4df3fb3f1397d6f6ddca929db4af
  canvas_page_name: /video/
  callback_url: http://localhost:3000/
  pretty_errors: true
  set_asset_host_to_callback_url: true
  tunnel:
    public_host_username:
    public_host:
    public_port: 4007
    local_port: 3000